fix(tui): worker path resolution in dev mode
Previous versions allowed:

```
bun install
bun dev ../path/to/my/project
```

But now I get:

```
% bun dev ../path/to/my/project
$ bun run --cwd packages/opencode --conditions=browser src/index.ts ../path/to/my/project
Error: Failed to change directory to /Users/cjs/repos/opencode/packages/path/to/my/project
```

If I try to add more ../ I get:

```
% bun dev ../../../path/to/my/project
$ bun run --cwd packages/opencode --conditions=browser src/index.ts ../../../path/to/my/project
ErrorEvent {
  type: "error",
  message: "BuildMessage: ModuleNotFound resolving \"./src/cli/cmd/tui/worker.ts\" (entry point)",
  error: null,
}
```

This commit fixes this by using relative path resolution.

There are actually two bugs fixed here:

Bun bug: https://github.com/oven-sh/bun/issues/15981

`bun run --cwd packages/opencode`, the `process.cwd()` returns the `--cwd` value
`packages/opencode`, not the directory the user ran "bun" within. This causes
`path.resolve(args.project)` to resolve relative paths from the wrong base dir.

We can use the URL object directly for worker path in dev mode.

Fixes: #3777

Co-authored-by: Sebastian Herrlinger <hasta84@gmail.com>
Signed-off-by: Christian Stewart <christian@cjs.zip>